project_id = "jmqnebzmlgjqbwtvkrja"

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.ad-event]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.admin-user-actions]
verify_jwt = true
