/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeekerRouteImport } from './routes/seeker'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeekerIndexRouteImport } from './routes/seeker.index'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SeekerSavedRouteImport } from './routes/seeker.saved'
import { Route as SeekerProfileRouteImport } from './routes/seeker.profile'
import { Route as SeekerApplicationsRouteImport } from './routes/seeker.applications'
import { Route as SeekerAlertsRouteImport } from './routes/seeker.alerts'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as EmployerTeamRouteImport } from './routes/employer.team'
import { Route as EmployerOnboardingRouteImport } from './routes/employer.onboarding'
import { Route as EmployerCandidatesRouteImport } from './routes/employer.candidates'
import { Route as EmployerBillingRouteImport } from './routes/employer.billing'
import { Route as EmployerAnalyticsRouteImport } from './routes/employer.analytics'
import { Route as EmployerAdsRouteImport } from './routes/employer.ads'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as EmployerJobsNewRouteImport } from './routes/employer.jobs.new'
import { Route as EmployerJobsIdEditRouteImport } from './routes/employer.jobs.$id.edit'
import { Route as EmployerJobsIdApplicantsRouteImport } from './routes/employer.jobs.$id.applicants'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerRoute = SeekerRouteImport.update({
  id: '/seeker',
  path: '/seeker',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerIndexRoute = SeekerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeekerRoute,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SeekerSavedRoute = SeekerSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => SeekerRoute,
} as any)
const SeekerProfileRoute = SeekerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SeekerRoute,
} as any)
const SeekerApplicationsRoute = SeekerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => SeekerRoute,
} as any)
const SeekerAlertsRoute = SeekerAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => SeekerRoute,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JobsRoute,
} as any)
const EmployerTeamRoute = EmployerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerOnboardingRoute = EmployerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerCandidatesRoute = EmployerCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerBillingRoute = EmployerBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerAnalyticsRoute = EmployerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerAdsRoute = EmployerAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => EmployerRoute,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const EmployerJobsNewRoute = EmployerJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerJobsIdEditRoute = EmployerJobsIdEditRouteImport.update({
  id: '/jobs/$id/edit',
  path: '/jobs/$id/edit',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerJobsIdApplicantsRoute =
  EmployerJobsIdApplicantsRouteImport.update({
    id: '/jobs/$id/applicants',
    path: '/jobs/$id/applicants',
    getParentRoute: () => EmployerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/employer': typeof EmployerRouteWithChildren
  '/faq': typeof FaqRoute
  '/jobs': typeof JobsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/seeker': typeof SeekerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/employer/ads': typeof EmployerAdsRoute
  '/employer/analytics': typeof EmployerAnalyticsRoute
  '/employer/billing': typeof EmployerBillingRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/onboarding': typeof EmployerOnboardingRoute
  '/employer/team': typeof EmployerTeamRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/seeker/alerts': typeof SeekerAlertsRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/profile': typeof SeekerProfileRoute
  '/seeker/saved': typeof SeekerSavedRoute
  '/admin/': typeof AdminIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/seeker/': typeof SeekerIndexRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/jobs/$id/applicants': typeof EmployerJobsIdApplicantsRoute
  '/employer/jobs/$id/edit': typeof EmployerJobsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/jobs': typeof JobsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/employer/ads': typeof EmployerAdsRoute
  '/employer/analytics': typeof EmployerAnalyticsRoute
  '/employer/billing': typeof EmployerBillingRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/onboarding': typeof EmployerOnboardingRoute
  '/employer/team': typeof EmployerTeamRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/seeker/alerts': typeof SeekerAlertsRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/profile': typeof SeekerProfileRoute
  '/seeker/saved': typeof SeekerSavedRoute
  '/admin': typeof AdminIndexRoute
  '/employer': typeof EmployerIndexRoute
  '/seeker': typeof SeekerIndexRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/jobs/$id/applicants': typeof EmployerJobsIdApplicantsRoute
  '/employer/jobs/$id/edit': typeof EmployerJobsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/employer': typeof EmployerRouteWithChildren
  '/faq': typeof FaqRoute
  '/jobs': typeof JobsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/seeker': typeof SeekerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/employer/ads': typeof EmployerAdsRoute
  '/employer/analytics': typeof EmployerAnalyticsRoute
  '/employer/billing': typeof EmployerBillingRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/onboarding': typeof EmployerOnboardingRoute
  '/employer/team': typeof EmployerTeamRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/seeker/alerts': typeof SeekerAlertsRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/profile': typeof SeekerProfileRoute
  '/seeker/saved': typeof SeekerSavedRoute
  '/admin/': typeof AdminIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/seeker/': typeof SeekerIndexRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/jobs/$id/applicants': typeof EmployerJobsIdApplicantsRoute
  '/employer/jobs/$id/edit': typeof EmployerJobsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/employer'
    | '/faq'
    | '/jobs'
    | '/pricing'
    | '/seeker'
    | '/sitemap.xml'
    | '/admin/ads'
    | '/admin/billing'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/users'
    | '/companies/$slug'
    | '/employer/ads'
    | '/employer/analytics'
    | '/employer/billing'
    | '/employer/candidates'
    | '/employer/onboarding'
    | '/employer/team'
    | '/jobs/$slug'
    | '/seeker/alerts'
    | '/seeker/applications'
    | '/seeker/profile'
    | '/seeker/saved'
    | '/admin/'
    | '/employer/'
    | '/seeker/'
    | '/employer/jobs/new'
    | '/employer/jobs/$id/applicants'
    | '/employer/jobs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/jobs'
    | '/pricing'
    | '/sitemap.xml'
    | '/admin/ads'
    | '/admin/billing'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/users'
    | '/companies/$slug'
    | '/employer/ads'
    | '/employer/analytics'
    | '/employer/billing'
    | '/employer/candidates'
    | '/employer/onboarding'
    | '/employer/team'
    | '/jobs/$slug'
    | '/seeker/alerts'
    | '/seeker/applications'
    | '/seeker/profile'
    | '/seeker/saved'
    | '/admin'
    | '/employer'
    | '/seeker'
    | '/employer/jobs/new'
    | '/employer/jobs/$id/applicants'
    | '/employer/jobs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/employer'
    | '/faq'
    | '/jobs'
    | '/pricing'
    | '/seeker'
    | '/sitemap.xml'
    | '/admin/ads'
    | '/admin/billing'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/users'
    | '/companies/$slug'
    | '/employer/ads'
    | '/employer/analytics'
    | '/employer/billing'
    | '/employer/candidates'
    | '/employer/onboarding'
    | '/employer/team'
    | '/jobs/$slug'
    | '/seeker/alerts'
    | '/seeker/applications'
    | '/seeker/profile'
    | '/seeker/saved'
    | '/admin/'
    | '/employer/'
    | '/seeker/'
    | '/employer/jobs/new'
    | '/employer/jobs/$id/applicants'
    | '/employer/jobs/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EmployerRoute: typeof EmployerRouteWithChildren
  FaqRoute: typeof FaqRoute
  JobsRoute: typeof JobsRouteWithChildren
  PricingRoute: typeof PricingRoute
  SeekerRoute: typeof SeekerRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker': {
      id: '/seeker'
      path: '/seeker'
      fullPath: '/seeker'
      preLoaderRoute: typeof SeekerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/': {
      id: '/seeker/'
      path: '/'
      fullPath: '/seeker/'
      preLoaderRoute: typeof SeekerIndexRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/employer/': {
      id: '/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seeker/saved': {
      id: '/seeker/saved'
      path: '/saved'
      fullPath: '/seeker/saved'
      preLoaderRoute: typeof SeekerSavedRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/seeker/profile': {
      id: '/seeker/profile'
      path: '/profile'
      fullPath: '/seeker/profile'
      preLoaderRoute: typeof SeekerProfileRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/seeker/applications': {
      id: '/seeker/applications'
      path: '/applications'
      fullPath: '/seeker/applications'
      preLoaderRoute: typeof SeekerApplicationsRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/seeker/alerts': {
      id: '/seeker/alerts'
      path: '/alerts'
      fullPath: '/seeker/alerts'
      preLoaderRoute: typeof SeekerAlertsRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof JobsRoute
    }
    '/employer/team': {
      id: '/employer/team'
      path: '/team'
      fullPath: '/employer/team'
      preLoaderRoute: typeof EmployerTeamRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/onboarding': {
      id: '/employer/onboarding'
      path: '/onboarding'
      fullPath: '/employer/onboarding'
      preLoaderRoute: typeof EmployerOnboardingRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/candidates': {
      id: '/employer/candidates'
      path: '/candidates'
      fullPath: '/employer/candidates'
      preLoaderRoute: typeof EmployerCandidatesRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/billing': {
      id: '/employer/billing'
      path: '/billing'
      fullPath: '/employer/billing'
      preLoaderRoute: typeof EmployerBillingRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/analytics': {
      id: '/employer/analytics'
      path: '/analytics'
      fullPath: '/employer/analytics'
      preLoaderRoute: typeof EmployerAnalyticsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/ads': {
      id: '/employer/ads'
      path: '/ads'
      fullPath: '/employer/ads'
      preLoaderRoute: typeof EmployerAdsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employer/jobs/new': {
      id: '/employer/jobs/new'
      path: '/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof EmployerJobsNewRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/jobs/$id/edit': {
      id: '/employer/jobs/$id/edit'
      path: '/jobs/$id/edit'
      fullPath: '/employer/jobs/$id/edit'
      preLoaderRoute: typeof EmployerJobsIdEditRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/jobs/$id/applicants': {
      id: '/employer/jobs/$id/applicants'
      path: '/jobs/$id/applicants'
      fullPath: '/employer/jobs/$id/applicants'
      preLoaderRoute: typeof EmployerJobsIdApplicantsRouteImport
      parentRoute: typeof EmployerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployerRouteChildren {
  EmployerAdsRoute: typeof EmployerAdsRoute
  EmployerAnalyticsRoute: typeof EmployerAnalyticsRoute
  EmployerBillingRoute: typeof EmployerBillingRoute
  EmployerCandidatesRoute: typeof EmployerCandidatesRoute
  EmployerOnboardingRoute: typeof EmployerOnboardingRoute
  EmployerTeamRoute: typeof EmployerTeamRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
  EmployerJobsNewRoute: typeof EmployerJobsNewRoute
  EmployerJobsIdApplicantsRoute: typeof EmployerJobsIdApplicantsRoute
  EmployerJobsIdEditRoute: typeof EmployerJobsIdEditRoute
}

const EmployerRouteChildren: EmployerRouteChildren = {
  EmployerAdsRoute: EmployerAdsRoute,
  EmployerAnalyticsRoute: EmployerAnalyticsRoute,
  EmployerBillingRoute: EmployerBillingRoute,
  EmployerCandidatesRoute: EmployerCandidatesRoute,
  EmployerOnboardingRoute: EmployerOnboardingRoute,
  EmployerTeamRoute: EmployerTeamRoute,
  EmployerIndexRoute: EmployerIndexRoute,
  EmployerJobsNewRoute: EmployerJobsNewRoute,
  EmployerJobsIdApplicantsRoute: EmployerJobsIdApplicantsRoute,
  EmployerJobsIdEditRoute: EmployerJobsIdEditRoute,
}

const EmployerRouteWithChildren = EmployerRoute._addFileChildren(
  EmployerRouteChildren,
)

interface JobsRouteChildren {
  JobsSlugRoute: typeof JobsSlugRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsSlugRoute: JobsSlugRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface SeekerRouteChildren {
  SeekerAlertsRoute: typeof SeekerAlertsRoute
  SeekerApplicationsRoute: typeof SeekerApplicationsRoute
  SeekerProfileRoute: typeof SeekerProfileRoute
  SeekerSavedRoute: typeof SeekerSavedRoute
  SeekerIndexRoute: typeof SeekerIndexRoute
}

const SeekerRouteChildren: SeekerRouteChildren = {
  SeekerAlertsRoute: SeekerAlertsRoute,
  SeekerApplicationsRoute: SeekerApplicationsRoute,
  SeekerProfileRoute: SeekerProfileRoute,
  SeekerSavedRoute: SeekerSavedRoute,
  SeekerIndexRoute: SeekerIndexRoute,
}

const SeekerRouteWithChildren =
  SeekerRoute._addFileChildren(SeekerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EmployerRoute: EmployerRouteWithChildren,
  FaqRoute: FaqRoute,
  JobsRoute: JobsRouteWithChildren,
  PricingRoute: PricingRoute,
  SeekerRoute: SeekerRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
