/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeekerRouteImport } from './routes/seeker'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeekerIndexRouteImport } from './routes/seeker.index'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as SeekerSavedRouteImport } from './routes/seeker.saved'
import { Route as SeekerProfileRouteImport } from './routes/seeker.profile'
import { Route as SeekerApplicationsRouteImport } from './routes/seeker.applications'
import { Route as SeekerAlertsRouteImport } from './routes/seeker.alerts'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as EmployerOnboardingRouteImport } from './routes/employer.onboarding'
import { Route as EmployerAdsRouteImport } from './routes/employer.ads'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as EmployerJobsNewRouteImport } from './routes/employer.jobs.new'
import { Route as EmployerJobsIdEditRouteImport } from './routes/employer.jobs.$id.edit'
import { Route as EmployerJobsIdApplicantsRouteImport } from './routes/employer.jobs.$id.applicants'

const SeekerRoute = SeekerRouteImport.update({
  id: '/seeker',
  path: '/seeker',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerIndexRoute = SeekerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeekerRoute,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployerRoute,
} as any)
const SeekerSavedRoute = SeekerSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => SeekerRoute,
} as any)
const SeekerProfileRoute = SeekerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SeekerRoute,
} as any)
const SeekerApplicationsRoute = SeekerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => SeekerRoute,
} as any)
const SeekerAlertsRoute = SeekerAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => SeekerRoute,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JobsRoute,
} as any)
const EmployerOnboardingRoute = EmployerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerAdsRoute = EmployerAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => EmployerRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const EmployerJobsNewRoute = EmployerJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerJobsIdEditRoute = EmployerJobsIdEditRouteImport.update({
  id: '/jobs/$id/edit',
  path: '/jobs/$id/edit',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerJobsIdApplicantsRoute =
  EmployerJobsIdApplicantsRouteImport.update({
    id: '/jobs/$id/applicants',
    path: '/jobs/$id/applicants',
    getParentRoute: () => EmployerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/employer': typeof EmployerRouteWithChildren
  '/faq': typeof FaqRoute
  '/jobs': typeof JobsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/seeker': typeof SeekerRouteWithChildren
  '/admin/ads': typeof AdminAdsRoute
  '/employer/ads': typeof EmployerAdsRoute
  '/employer/onboarding': typeof EmployerOnboardingRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/seeker/alerts': typeof SeekerAlertsRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/profile': typeof SeekerProfileRoute
  '/seeker/saved': typeof SeekerSavedRoute
  '/employer/': typeof EmployerIndexRoute
  '/seeker/': typeof SeekerIndexRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/jobs/$id/applicants': typeof EmployerJobsIdApplicantsRoute
  '/employer/jobs/$id/edit': typeof EmployerJobsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/jobs': typeof JobsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/admin/ads': typeof AdminAdsRoute
  '/employer/ads': typeof EmployerAdsRoute
  '/employer/onboarding': typeof EmployerOnboardingRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/seeker/alerts': typeof SeekerAlertsRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/profile': typeof SeekerProfileRoute
  '/seeker/saved': typeof SeekerSavedRoute
  '/employer': typeof EmployerIndexRoute
  '/seeker': typeof SeekerIndexRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/jobs/$id/applicants': typeof EmployerJobsIdApplicantsRoute
  '/employer/jobs/$id/edit': typeof EmployerJobsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/employer': typeof EmployerRouteWithChildren
  '/faq': typeof FaqRoute
  '/jobs': typeof JobsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/seeker': typeof SeekerRouteWithChildren
  '/admin/ads': typeof AdminAdsRoute
  '/employer/ads': typeof EmployerAdsRoute
  '/employer/onboarding': typeof EmployerOnboardingRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/seeker/alerts': typeof SeekerAlertsRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/profile': typeof SeekerProfileRoute
  '/seeker/saved': typeof SeekerSavedRoute
  '/employer/': typeof EmployerIndexRoute
  '/seeker/': typeof SeekerIndexRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/jobs/$id/applicants': typeof EmployerJobsIdApplicantsRoute
  '/employer/jobs/$id/edit': typeof EmployerJobsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/employer'
    | '/faq'
    | '/jobs'
    | '/pricing'
    | '/seeker'
    | '/admin/ads'
    | '/employer/ads'
    | '/employer/onboarding'
    | '/jobs/$slug'
    | '/seeker/alerts'
    | '/seeker/applications'
    | '/seeker/profile'
    | '/seeker/saved'
    | '/employer/'
    | '/seeker/'
    | '/employer/jobs/new'
    | '/employer/jobs/$id/applicants'
    | '/employer/jobs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/jobs'
    | '/pricing'
    | '/admin/ads'
    | '/employer/ads'
    | '/employer/onboarding'
    | '/jobs/$slug'
    | '/seeker/alerts'
    | '/seeker/applications'
    | '/seeker/profile'
    | '/seeker/saved'
    | '/employer'
    | '/seeker'
    | '/employer/jobs/new'
    | '/employer/jobs/$id/applicants'
    | '/employer/jobs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/employer'
    | '/faq'
    | '/jobs'
    | '/pricing'
    | '/seeker'
    | '/admin/ads'
    | '/employer/ads'
    | '/employer/onboarding'
    | '/jobs/$slug'
    | '/seeker/alerts'
    | '/seeker/applications'
    | '/seeker/profile'
    | '/seeker/saved'
    | '/employer/'
    | '/seeker/'
    | '/employer/jobs/new'
    | '/employer/jobs/$id/applicants'
    | '/employer/jobs/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EmployerRoute: typeof EmployerRouteWithChildren
  FaqRoute: typeof FaqRoute
  JobsRoute: typeof JobsRouteWithChildren
  PricingRoute: typeof PricingRoute
  SeekerRoute: typeof SeekerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seeker': {
      id: '/seeker'
      path: '/seeker'
      fullPath: '/seeker'
      preLoaderRoute: typeof SeekerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/': {
      id: '/seeker/'
      path: '/'
      fullPath: '/seeker/'
      preLoaderRoute: typeof SeekerIndexRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/employer/': {
      id: '/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/seeker/saved': {
      id: '/seeker/saved'
      path: '/saved'
      fullPath: '/seeker/saved'
      preLoaderRoute: typeof SeekerSavedRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/seeker/profile': {
      id: '/seeker/profile'
      path: '/profile'
      fullPath: '/seeker/profile'
      preLoaderRoute: typeof SeekerProfileRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/seeker/applications': {
      id: '/seeker/applications'
      path: '/applications'
      fullPath: '/seeker/applications'
      preLoaderRoute: typeof SeekerApplicationsRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/seeker/alerts': {
      id: '/seeker/alerts'
      path: '/alerts'
      fullPath: '/seeker/alerts'
      preLoaderRoute: typeof SeekerAlertsRouteImport
      parentRoute: typeof SeekerRoute
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof JobsRoute
    }
    '/employer/onboarding': {
      id: '/employer/onboarding'
      path: '/onboarding'
      fullPath: '/employer/onboarding'
      preLoaderRoute: typeof EmployerOnboardingRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/ads': {
      id: '/employer/ads'
      path: '/ads'
      fullPath: '/employer/ads'
      preLoaderRoute: typeof EmployerAdsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employer/jobs/new': {
      id: '/employer/jobs/new'
      path: '/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof EmployerJobsNewRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/jobs/$id/edit': {
      id: '/employer/jobs/$id/edit'
      path: '/jobs/$id/edit'
      fullPath: '/employer/jobs/$id/edit'
      preLoaderRoute: typeof EmployerJobsIdEditRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/jobs/$id/applicants': {
      id: '/employer/jobs/$id/applicants'
      path: '/jobs/$id/applicants'
      fullPath: '/employer/jobs/$id/applicants'
      preLoaderRoute: typeof EmployerJobsIdApplicantsRouteImport
      parentRoute: typeof EmployerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployerRouteChildren {
  EmployerAdsRoute: typeof EmployerAdsRoute
  EmployerOnboardingRoute: typeof EmployerOnboardingRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
  EmployerJobsNewRoute: typeof EmployerJobsNewRoute
  EmployerJobsIdApplicantsRoute: typeof EmployerJobsIdApplicantsRoute
  EmployerJobsIdEditRoute: typeof EmployerJobsIdEditRoute
}

const EmployerRouteChildren: EmployerRouteChildren = {
  EmployerAdsRoute: EmployerAdsRoute,
  EmployerOnboardingRoute: EmployerOnboardingRoute,
  EmployerIndexRoute: EmployerIndexRoute,
  EmployerJobsNewRoute: EmployerJobsNewRoute,
  EmployerJobsIdApplicantsRoute: EmployerJobsIdApplicantsRoute,
  EmployerJobsIdEditRoute: EmployerJobsIdEditRoute,
}

const EmployerRouteWithChildren = EmployerRoute._addFileChildren(
  EmployerRouteChildren,
)

interface JobsRouteChildren {
  JobsSlugRoute: typeof JobsSlugRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsSlugRoute: JobsSlugRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface SeekerRouteChildren {
  SeekerAlertsRoute: typeof SeekerAlertsRoute
  SeekerApplicationsRoute: typeof SeekerApplicationsRoute
  SeekerProfileRoute: typeof SeekerProfileRoute
  SeekerSavedRoute: typeof SeekerSavedRoute
  SeekerIndexRoute: typeof SeekerIndexRoute
}

const SeekerRouteChildren: SeekerRouteChildren = {
  SeekerAlertsRoute: SeekerAlertsRoute,
  SeekerApplicationsRoute: SeekerApplicationsRoute,
  SeekerProfileRoute: SeekerProfileRoute,
  SeekerSavedRoute: SeekerSavedRoute,
  SeekerIndexRoute: SeekerIndexRoute,
}

const SeekerRouteWithChildren =
  SeekerRoute._addFileChildren(SeekerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EmployerRoute: EmployerRouteWithChildren,
  FaqRoute: FaqRoute,
  JobsRoute: JobsRouteWithChildren,
  PricingRoute: PricingRoute,
  SeekerRoute: SeekerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
